import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <header className='bg-white py-[28px] px-[80px] flex items-center'>
          <p className='text-[30px] font-semibold'>LOGO</p>
          <p className='text-dark-blue mx-auto w-[100%] max-w-[320px] text-[19px] items-center flex justify-center'>
            Current survey name
          </p>
        </header>
        <div className='w-[100%] max-w-[846px] mx-auto p-[42px] bg-content-wrapper-bg rounded-[6px] border-[1px] border-solid'>
          {children}
        </div>
      </body>
    </html>
  );
}
