import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} h-screen`}>
        <header className='bg-white py-[2px] px-[28px] sm:py-[28px] sm:px-[80px]'>
          <div className='relative flex items-center'>
            <p className='text-[18px] sm:text-[30px] font-semibold absolute left-0'>
              LOGO
            </p>
            <p className='text-dark-blue mx-auto w-[100%] text-[19px] text-center'>
              Current survey name
            </p>
          </div>
        </header>
        <div className='w-[100%] sm:max-w-[846px] mx-auto h-[calc(100%_-_49px)] sm:h-[calc(100%_-_101px)]'>
          {children}
        </div>
      </body>
    </html>
  );
}
